"""
api/app.py
───────────
FastAPI application for MindScope — Mental Health NLP inference API.

Run with:
    uvicorn api.app:app --reload

Or from the project root (so src/ imports resolve correctly):
    uvicorn api.app:app --reload --app-dir .

Endpoints
─────────
  GET  /           → welcome message
  GET  /health     → liveness check + loaded model info
  POST /predict    → classify text + sentiment + severity
  GET  /classes    → list the 5 supported condition labels
  GET  /docs       → Swagger UI (auto-generated by FastAPI)

Design rules followed
──────────────────────
  - app.py only defines ROUTES — no ML logic lives here
  - All ML logic lives in api/inference.py
  - All artifact loading lives in api/model_loader.py
  - All data shapes live in api/schemas.py
  - No bare print() — logging via src/utils/logger.py
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from api.model_loader import load_artifacts, get_registry
from api.inference import run_inference
from api.schemas import (
    PredictRequest,
    PredictResponse,
    HealthResponse,
    ErrorResponse,
)
from src.utils.config import CLASSES, API_CONFIG
from src.utils.logger import get_logger

logger = get_logger(__name__)


# ══════════════════════════════════════════════════════════════════════
# Lifespan — runs once at startup and shutdown
# ══════════════════════════════════════════════════════════════════════

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load ML artifacts before the server starts accepting requests."""
    logger.info("[app] Server starting — loading ML artifacts ...")
    load_artifacts()
    logger.info("[app] ✓ Artifacts loaded — server is ready")
    yield
    # Any teardown logic would go here
    logger.info("[app] Server shutting down")


# ══════════════════════════════════════════════════════════════════════
# App instance
# ══════════════════════════════════════════════════════════════════════

app = FastAPI(
    title="MindScope API",
    description=(
        "Mental health NLP classification API. "
        "Classifies Reddit-style text into one of 5 conditions: "
        "ADHD, Aspergers, Depression, OCD, PTSD.\n\n"
        "⚠️ **Not a clinical tool.** For research and demonstration only."
    ),
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
)

# Allow all origins during development — restrict in production
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ══════════════════════════════════════════════════════════════════════
# Global exception handler — returns clean JSON on unexpected errors
# ══════════════════════════════════════════════════════════════════════

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.error(f"[app] Unhandled exception: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": f"Internal server error: {str(exc)}"},
    )


# ══════════════════════════════════════════════════════════════════════
# Routes
# ══════════════════════════════════════════════════════════════════════

@app.get("/", tags=["General"])
def root():
    """Welcome endpoint."""
    return {
        "message": "Welcome to the MindScope Mental Health NLP API 🧠",
        "docs":    "/docs",
        "predict": "/predict",
    }


# ──────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["General"],
    summary="Liveness check",
)
def health():
    """
    Returns HTTP 200 when the server is running and models are loaded.
    Useful for container health probes and uptime monitors.
    """
    registry = get_registry()
    backend  = registry["backend"]
    model_name = (
        API_CONFIG["classical_model_name"]
        if backend == "classical"
        else "bert-base-uncased (fine-tuned)"
    )
    return HealthResponse(status="ok", backend=backend, model=model_name)


# ──────────────────────────────────────────────────────────────────────

@app.get("/classes", tags=["General"], summary="List supported condition classes")
def classes():
    """Returns the 5 mental health condition labels the model predicts."""
    return {"classes": CLASSES}


# ──────────────────────────────────────────────────────────────────────

@app.post(
    "/predict",
    response_model=PredictResponse,
    tags=["Inference"],
    summary="Classify a text post",
    responses={
        200: {"description": "Successful prediction"},
        422: {"description": "Validation error — input too short or malformed"},
        500: {"model": ErrorResponse, "description": "Internal model error"},
    },
)
def predict(request: PredictRequest):
    """
    Classify a Reddit-style mental health post.

    ### Input
    ```json
    { "text": "I feel anxious all the time and can't stop worrying." }
    ```

    ### Output
    - **prediction** — most likely condition (adhd / aspergers / depression / ocd / ptsd)
    - **confidence** — model's probability for that prediction (0–1)
    - **all_scores** — probabilities for all 5 classes
    - **sentiment** — positive / negative / neutral (VADER)
    - **sentiment_scores** — full VADER neg / neu / pos / compound breakdown
    - **severity** — heuristic severity estimate: low / moderate / high
    - **clean_text** — preprocessed input for transparency

    ⚠️ This is a research tool, not a diagnostic instrument.
    """
    logger.info(f"[app] POST /predict — text length: {len(request.text)} chars")

    try:
        result = run_inference(request.text)
    except Exception as exc:
        logger.error(f"[app] Inference failed: {exc}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(exc))

    return PredictResponse(**result)